#!/bin/sh -efuC
set -o pipefail

# An easy way to get access from inside hasher to some local repo is via ssh.
# (Of course, there can be some security implications when you share network
# with hasher and give it access via ssh.)

case "$1" in
    -u|--update)
	readonly UPDATE=yes
	shift
	;;
    *)
	readonly UPDATE=
	;;
esac
hshdir="$(eval "$(hsh --printenv "$@")" && echo "$workdir")"
readonly hshdir

MY="$(dirname -- "$(realpath -- "$0")")"
readonly MY
set -x

hsh-install "$@" -- apt

readonly FIELD_RE_FMT='[[:blank:]]*%s[[:blank:]]+'
printf -v TYPE_RE "$FIELD_RE_FMT" '[^[:blank:]]+'
readonly TYPE_RE
printf -v SIG_RE "$FIELD_RE_FMT" '\[[^]]*\]'
readonly SIG_RE
# We process the only sources.list filled out by mkaptbox.
# We don't honor comments (i.e., edit URIs inside them, too).
<"$hshdir"/aptbox/etc/apt/sources.list \
 sed -Ee "s,^($TYPE_RE($SIG_RE)?)file:/,\1ssh://localhost/," \
    | "$MY"/hsh-write --rooter "$@" -- /etc/apt/sources.list

# Note that any /etc/apt/sources.list.d/* are not affected.

[ -n "$UPDATE" ] || exit 0

share_network=1 \
	     hsh-run --rooter "$@" \
	     -- apt-get update \
	     </dev/null
